#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CoreApp.Droid.Resource", IsApplication=false)]

namespace CoreApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public static int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public static int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public static int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public static int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public static int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public static int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public static int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public static int calendar_text_selector = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public static int calendar_text_unselectable = 2131034122;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public static int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int calendar_text_small = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int calendar_bg_selector = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public static int calendar_grid = 2131230724;
			
			// aapt resource value: 0x7f080001
			public static int calendar_view = 2131230721;
			
			// aapt resource value: 0x7f080003
			public static int left_arrow = 2131230723;
			
			// aapt resource value: 0x7f080002
			public static int right_arrow = 2131230722;
			
			// aapt resource value: 0x7f080000
			public static int title = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int month = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public static int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public static int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040004
			public static int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public static int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int month_name_format = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public static int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public static int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
