# This is a basic workflow to help you get started with Actions

name: CI on Push and Pull Request

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  android-build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Android build
      run: |
        cd src
        nuget restore
        cd DemoApp\DemoApp.Droid
        msbuild DemoApp.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
      shell: powershell

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: PCLAppConfig.1.0.2.nupkg
        path: ../src/build
